[[section-introduction-and-goals]]
==	Einführung und Ziele

[role="arc42help"]
****
Beschreibt die wesentlichen Anforderungen und treibenden Kräfte, die bei der Umsetzung der Softwarearchitektur und Entwicklung des Systems berücksichtigt werden müssen.

Dazu gehören:

* zugrunde liegende Geschäftsziele,
* wesentliche Aufgabenstellungen,
* wesentliche funktionale Anforderungen,
* Qualitätsziele für die Architektur und
* relevante Stakeholder und deren Erwartungshaltung.
****

=== Aufgabenstellung
****
Die Kurzbeschreibung des Kunden lautet wie folgt:

Strom wird im Alltag oft unbewusst verbraucht. Wir lassen Lichter brennen, Geräte werden nicht komplett vom Stromnetz getrennt, Computer werden nicht heruntergefahren. Fast in allen Lebensbereichen sind wir auf Strom angewiesen, sei dies im Transport, Haushalt oder auf der Arbeit. Trotzdem haben viele Menschen kein Verständnis für die Menge an Strom, die sie verbrauchen und gehen verschwenderisch mit Strom um. In diesem Projekt soll ein Spiel entwickelt werden, welches ein Bewusstsein für den Stromverbrauch im Alltag schafft und zum Strom sparen anregt.
****

=== Qualitätsziele
****
Die wichtigsten Qualitätsanforderungen an die Architektur sind folgende:

* **Erlernbarkeit** +
  Die Architektur soll einfach verständlich und erlernbar sein, damit alle Teammitglieder bei der Programmierung mithelfen können, ohne grössere Zeitinvestments um sich in die Architektur einzuarbeiten.
* **Funktionale Eignung** +
  Die Architektur soll sich für das Projekt gut eignen. Dabei ist vor allem auf die Komplexität Acht zu geben, denn durch höhere Komplexität steigt zwar potentiell die Wartbarkeit in der Zukunft, die Entwicklung wird aber verlangsamt und erschwert.
* **Zuverlässigkeit** +
  Die Architektur soll Zuverlässig funktionieren. Das heisst es muss damit gerechnet werden, dass unerwartete Inputs generiert werden, diese aber nicht zu einem Absturz des Systems führen.
****

=== Stakeholder

[role="arc42help"]
****
.Inhalt
Expliziter Überblick über die Stakeholder des Systems – über alle Personen, Rollen oder Organisationen –, die

* die Architektur kennen sollten oder
* von der Architektur überzeugt werden müssen,
* mit der Architektur oder dem Code arbeiten (z.B. Schnittstellen nutzen),
* die Dokumentation der Architektur für ihre eigene Arbeit benötigen,
* Entscheidungen über das System und dessen Entwicklung treffen.

.Motivation
Sie sollten die Projektbeteiligten und -betroffenen kennen, sonst erleben Sie später im Entwicklungsprozess Überraschungen.
Diese Stakeholder bestimmen unter anderem Umfang und Detaillierungsgrad der von Ihnen zu leistenden Arbeit und Ergebnisse.

.Form
Tabelle mit Rollen- oder Personennamen, sowie deren Erwartungshaltung bezüglich der Architektur und deren Dokumentation.
****

[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| _<Rolle-1>_ | _<Kontakt-1>_ | _<Erwartung-1>_
| _<Rolle-2>_ | _<Kontakt-2>_ | _<Erwartung-2>_ 
|===
