[[section-introduction-and-goals]]
== Einführung und Ziele
=== Aufgabenstellung
****
Die Kurzbeschreibung des Kunden lautet wie folgt:

Strom wird im Alltag oft unbewusst verbraucht. Wir lassen Lichter brennen, Geräte werden nicht komplett vom Stromnetz getrennt, Computer werden nicht heruntergefahren. Fast in allen Lebensbereichen sind wir auf Strom angewiesen, sei dies im Transport, Haushalt oder auf der Arbeit. Trotzdem haben viele Menschen kein Verständnis für die Menge an Strom, die sie verbrauchen und gehen verschwenderisch mit Strom um. In diesem Projekt soll ein Spiel entwickelt werden, welches ein Bewusstsein für den Stromverbrauch im Alltag schafft und zum Strom sparen anregt.
****

=== Qualitätsziele
****
Die wichtigsten Qualitätsanforderungen an die Architektur sind folgende:

* **Erlernbarkeit** +
  Die Architektur soll einfach verständlich und erlernbar sein, damit alle Teammitglieder bei der Programmierung mithelfen können, ohne grössere Zeitinvestments um sich in die Architektur einzuarbeiten.
* **Funktionale Eignung** +
  Die Architektur soll sich für das Projekt gut eignen. Dabei ist vor allem auf die Komplexität Acht zu geben, denn durch höhere Komplexität steigt zwar potentiell die Wartbarkeit in der Zukunft, die Entwicklung wird aber verlangsamt und erschwert.
* **Zuverlässigkeit** +
  Die Architektur soll Zuverlässig funktionieren. Das heisst es muss damit gerechnet werden, dass unerwartete Inputs generiert werden, diese aber nicht zu einem Absturz des Systems führen.
****

=== Stakeholder
[cols="1,1,2" options="header"]
|===
|Rolle |Kontakt |Erwartungshaltung
| Auftraggeber | Primeo Energie | gute Dokumentation und Wartbarkeit für den Betrieb des Systems
| Kunden | Cédric Merz, Hannah Sarah Kühne | geeignete Architektur für einen sauberen Projektverlauf
| Teammitglieder allgemein | Andrin Martig, Daniel Barber, Samuel Burkhardt, Damjan Mlinar, Hoang Viet Nguyen, Viktor Weilenmann, Marco Worni | erlernbare Architektur, gute Dokumentation für einfache zusammenarbeit
| Testmanager | Damjan Mlinar | Testbarkeit der Funktionen der Software
| Requirements-Engineer | Viktor Weilenmann | angemessene Architektur entsprechend den Requirements
|===
