[[section-design-decisions]]
== Architekturentscheidungen

////
[role="arc42help"]
****
.Inhalt
Wichtige, teure, große oder riskante Architektur- oder Entwurfsentscheidungen inklusive der jeweiligen Begründungen.
Mit "Entscheidungen" meinen wir hier die Auswahl einer von mehreren Alternativen unter vorgegebenen Kriterien.

Wägen Sie ab, inwiefern Sie Entscheidungen hier zentral beschreiben, oder wo eine lokale Beschreibung (z.B. in der Whitebox-Sicht von Bausteinen) sinnvoller ist.
Vermeiden Sie Redundanz.
Verweisen Sie evtl. auf Abschnitt 4, wo schon grundlegende strategische Entscheidungen beschrieben wurden.

.Motivation
Stakeholder des Systems sollten wichtige Entscheidungen verstehen und nachvollziehen können.

.Form
Verschiedene Möglichkeiten:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) für jede wichtige Entscheidung
* Liste oder Tabelle, nach Wichtigkeit und Tragweite der Entscheidungen geordnet
* ausführlicher in Form einzelner Unterkapitel je Entscheidung

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-9/[Architekturentscheidungen] in der arc42 Dokumentation (auf Englisch!).
Dort finden Sie Links und Beispiele zum Thema ADR.

****
////

=== Libraries
* *FXGL* +
FXGL erlaubte uns extrem schnell einen funktionierenden Prototypen zu entwickeln, schränkt das Development aber in gewissen Entscheidungen ein (viele Funktionen werden schon von der Library zur Verfügung gestellt, aber sind teilweise nur schwer anpassbar).
** GitHub: https://github.com/AlmasB/FXGL
** Docs: https://github.com/AlmasB/FXGL/wiki/FXGL-11
** Example Games: https://github.com/AlmasB/FXGLGames/
** YouToube Videos: https://www.youtube.com/playlist?list=PL4h6ypqTi3RTiTuAQFKE6xwflnPKyFuPp[FXGL - JavaFX Game Engine Playlist]
* *Pi4J* +
Pi4J stellt eine Java API für I/O auf dem Raspberry Pi zur Verfügung.
** Webseite: https://pi4j.com
** GitHub: https://github.com/Pi4J/pi4j-v2
* *Pi4J Example Components* +
Die Pi4J Example Components Library verfügt über eine breite Auswahl an Klassen für die Kommunikation mit Hardwarekomponenten. Die Library wurde in der FHNW entwickelt wodurch wir bei Problemen schnell und einfach Support erhalten.
** GitHub: https://github.com/Pi4J/pi4j-example-components

=== Architektur Patterns
* *MVC* +
Wir richten uns bei der Architektur grob am Model-View-Controller Pattern, jedoch erschwert FXGL teilweise eine 100% saubere Trennung der Klassen.

=== Weitere Ressourcen
* *CrowPI OS* +
Das CrowPi OS ist ein Betriebssystem für den Raspberry Pi, welches Out-of-the-box Support für Java 17 und JavaFX Applikationen bietet.
** GitHub: https://github.com/Pi4J/pi4j-os
** Docs: https://pi4j.com/getting-started/crowpi/crowpi-os/
** JavaFX Template Project: https://github.com/Pi4J/pi4j-template-javafx
