[[section-solution-strategy]]
== Lösungsstrategie

[cols="1,2,1" options="header"]
|===
|Ziel/Requirement|Architektonischer Ansatz|Details
|Erlernbarkeit|Das MVC Pattern hilt unseren Code leserlicher zu gestalten zu dem wurde während der erstellung der Software darauf geachtet alles möglich einfach zu halten.|<<section-concepts, MVC Pattern>>
|Funktionale Eignung|FXGL und JavaFX eigenen sich ein Spiel herzustellen. Pi4j braucht es um den Kontroller mit dem Raspberry nutzen zu können.|<<section-technical-risks, Libraries>>
|Zuverlässigkeit|Junit, Mockito und manuelle Tests wurden genutzt um die Zuverlässigkeit zu steigern| https://gitlab.fhnw.ch/ip12-22vt/ip12-22vt_strombewusst/docu/-/blob/main/testing/Testplan.adoc/[Testplan]
|===

////
[role="arc42help"]
****
.Inhalt
Kurzer Überblick über die grundlegenden Entscheidungen und Lösungsansätze, die Entwurf und Implementierung des Systems prägen.
Hierzu gehören:

* Technologieentscheidungen
* Entscheidungen über die Top-Level-Zerlegung des Systems, beispielsweise die Verwendung gesamthaft prägender Entwurfs- oder Architekturmuster,
* Entscheidungen zur Erreichung der wichtigsten Qualitätsanforderungen sowie
* relevante organisatorische Entscheidungen, beispielsweise für bestimmte Entwicklungsprozesse oder Delegation bestimmter Aufgaben an andere Stakeholder.

.Motivation
Diese wichtigen Entscheidungen bilden wesentliche „Eckpfeiler“ der Architektur.
Von ihnen hängen viele weitere Entscheidungen oder Implementierungsregeln ab.

.Form
Fassen Sie die zentralen Entwurfsentscheidungen *kurz* zusammen.
Motivieren Sie, ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben.
Vermeiden Sie redundante Beschreibungen und verweisen Sie eher auf weitere Ausführungen in Folgeabschnitten.

.Weiterführende Informationen

Siehe https://docs.arc42.org/section-4/[Lösungsstrategie] in der online-Dokumentation (auf Englisch!).
****
////
