= Systemidee Projekt Strom Bewusst

== Kernaufgabe des Systems
****
Ziel des Projektes Strom Bewusst ist es, ein Spiel für das Erlebniscenter Kosmos von Primeo Energie zu schaffen. Das Spiel soll Kindern näherbringen wie viel Strom im Alltag verbraucht wird, oft auch ohne dass es uns bewusst ist und Tipps und Tricks zum Stromsparen vermitteln.
****

== Kategorie von System
****
Unser Projekt ist ein operationales System, jedoch ohne externe Schnittstellen. Ausserdem hat unser System einige Eigenschaften eines Eingebetteten Systems, da wir spezielle Hardware und Peripherie für unser Projekt verwenden werden.
****

== Wesentliche Qualitätsanforderungen
****
Unser Team hat folgende Qualitätsanforderungen (nach https://de.wikipedia.org/wiki/ISO/IEC_9126[DIN/ISO 9126]) als besonders wichtig für das System identifiziert:

* **Benutzbarkeit**, insbesondere Erlenbarkeit und Attraktivität
  Wichtig weil das Projekt unsere Zielgruppe fesseln soll
* **Zuverlässigkeit**, insbesondere Fehlertoleranz
  Wichtig weil der administrationsaufwand für Primeo Energie möglichst klein sein soll
* **Funktionalität**, insbesondere Angemessenheit
  Wichtig weil wir sicherstellen wollen, dass unser System für die Ausstellung der Primeo Energie geeignet ist

Es gibt ausserdem einige Qualitätsanforderungen die für unser Projekt weniger relevant sind, namentlich Sicherheit, da das System weder Schnittstellen auf externe Systeme hat, noch speziell schützenswerte Daten verarbeitet werden, die gesamte Übertragbarkeit, da unser System einen spezialisierten Anwendungsfall hat und einzigartig sein wird und Effizienz, da diese auf das Spielerlebnis nur wenig Einfluss hat.
****

== Relevante Stakeholder
****
Welche Rollen oder Personen (= Stakeholder) innerhalb oder ausserhalt der Organisation haben ein Interesse am System? Beispiele sind Benutzer der Kernfunktionalität („Anwender“), Administratoren und Betreiber, Benutzer mit Sonderfunktionen.

**Auftraggeber:** +
Primeo Energie

Die Primeo Energie wird nach Projektabschluss das System in ihrer Ausstellung in Betrieb nehmen und administrireren.

**Kunden:**

* Cédric Merz
* Hannah Sarah Kühne

**Teammitglieder:**

* Andrin Martig
* Daniel Barber
* Samuel Burkhardt
* Damjan Mlinar
* Hoang Viet Nguyen
* Viktor Weilenmann
* Marco Worni

**Benutzer:** +
Zielgruppe sind 12 - 16 jährige Kinder welche die Ausstellung der Primeo Energie besuchen
****

== Schnittstellen zu externen Systemen
****
Das System ist in sich geschlossen. Es gibt keine Schnittstellen zu externen Systemen.
****